# Generated by Django 5.2.6 on 2025-09-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdata',
            name='room_hour',
        ),
        migrations.AddField(
            model_name='roomdata',
            name='available_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
