# Generated by Django 5.2.6 on 2025-09-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=6)),
                ('room_name', models.CharField(max_length=10)),
                ('room_capacity', models.IntegerField()),
                ('room_hour', models.TimeField()),
                ('room_available', models.BooleanField()),
            ],
        ),
    ]
